export const QR_TYPES = [
  {
    id: 'url',
    name: 'URL',
    title: 'URL QR Code Generator',
    description: 'Generate QR codes for any website URL. Scan to open links instantly.',
    icon: '🔗',
    path: '/qr/url',
    metaDescription: 'Free URL QR code generator. Create QR codes for any website link. Download as PNG, SVG, or PDF. No signup required.',
    keywords: 'url qr code, link qr code, website qr code, qr code generator',
  },
  {
    id: 'text',
    name: 'Text',
    title: 'Text QR Code Generator',
    description: 'Encode any text message into a QR code.',
    icon: '📝',
    path: '/qr/text',
    metaDescription: 'Free text QR code generator. Encode any message into a scannable QR code. Download in multiple formats.',
    keywords: 'text qr code, message qr code, plain text qr code',
  },
  {
    id: 'wifi',
    name: 'WiFi',
    title: 'WiFi QR Code Generator',
    description: 'Share WiFi credentials via QR code. Scan to connect instantly.',
    icon: '📶',
    path: '/qr/wifi',
    metaDescription: 'Free WiFi QR code generator. Share your WiFi password via QR code. Guests scan to connect automatically.',
    keywords: 'wifi qr code, wifi password qr code, share wifi qr code',
  },
  {
    id: 'vcard',
    name: 'vCard',
    title: 'vCard QR Code Generator',
    description: 'Create digital business cards as QR codes with contact details.',
    icon: '👤',
    path: '/qr/vcard',
    metaDescription: 'Free vCard QR code generator. Create digital business cards with name, phone, email, and address.',
    keywords: 'vcard qr code, business card qr code, contact qr code',
  },
  {
    id: 'email',
    name: 'Email',
    title: 'Email QR Code Generator',
    description: 'Generate QR codes that open a pre-filled email.',
    icon: '✉️',
    path: '/qr/email',
    metaDescription: 'Free email QR code generator. Create QR codes with pre-filled recipient, subject, and body.',
    keywords: 'email qr code, mailto qr code',
  },
  {
    id: 'sms',
    name: 'SMS',
    title: 'SMS QR Code Generator',
    description: 'Create QR codes that send a pre-filled SMS message.',
    icon: '💬',
    path: '/qr/sms',
    metaDescription: 'Free SMS QR code generator. Create QR codes that open a text message with pre-filled content.',
    keywords: 'sms qr code, text message qr code',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    title: 'WhatsApp QR Code Generator',
    description: 'Create QR codes to start a WhatsApp chat with pre-filled message.',
    icon: '💚',
    path: '/qr/whatsapp',
    metaDescription: 'Free WhatsApp QR code generator. Create QR codes to start WhatsApp conversations instantly.',
    keywords: 'whatsapp qr code, whatsapp link qr code, wa.me qr code',
  },
  {
    id: 'upi',
    name: 'UPI Payment',
    title: 'UPI Payment QR Code Generator',
    description: 'Generate UPI payment QR codes for instant money transfers.',
    icon: '₹',
    path: '/qr/upi',
    metaDescription: 'Free UPI payment QR code generator. Create UPI QR codes for Google Pay, PhonePe, Paytm. Accept payments instantly.',
    keywords: 'upi qr code, upi payment qr code, google pay qr code, phonepe qr code',
  },
  {
    id: 'phone',
    name: 'Phone Call',
    title: 'Phone Call QR Code Generator',
    description: 'Create QR codes that dial a phone number when scanned.',
    icon: '📞',
    path: '/qr/phone',
    metaDescription: 'Free phone call QR code generator. Create QR codes that dial a number instantly when scanned.',
    keywords: 'phone qr code, call qr code, tel qr code',
  },
  {
    id: 'location',
    name: 'Location',
    title: 'Location QR Code Generator',
    description: 'Share locations via QR code using coordinates or map links.',
    icon: '📍',
    path: '/qr/location',
    metaDescription: 'Free location QR code generator. Share GPS coordinates or map locations via scannable QR codes.',
    keywords: 'location qr code, gps qr code, map qr code, google maps qr code',
  },
  {
    id: 'event',
    name: 'Event',
    title: 'Calendar Event QR Code Generator',
    description: 'Create QR codes for calendar events in iCal format.',
    icon: '📅',
    path: '/qr/event',
    metaDescription: 'Free calendar event QR code generator. Create QR codes for events with date, time, and location in iCal format.',
    keywords: 'event qr code, calendar qr code, ical qr code',
  },
  {
    id: 'appstore',
    name: 'App Store',
    title: 'App Store QR Code Generator',
    description: 'Link to your iOS or Android app via QR code.',
    icon: '📱',
    path: '/qr/appstore',
    metaDescription: 'Free App Store QR code generator. Create QR codes linking to iOS App Store or Google Play apps.',
    keywords: 'app store qr code, google play qr code, app download qr code',
  },
]
